name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - name: Just some echo
              run: echo "Hello, World!"
